services:

  backend:
    container_name: core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=prod # Use ENV=${ENV} to pass environment variables from the .env file

      # Add more environment variables here
